### ISSUE TITLE
AR_视频播放问题

### ISSUE THREAD

**Issue by NQPE** [baidu/AR#1]
1.使用AR/AR_Sample/ar-tracking-video/ar/ 下的透明视频demo 透明视频无法显示出来
2.使用AR/AR_Sample/ar-video/ar/ 下的视频demo 视频可以显示出来 但是却是一进入ARActivity页面就显示视频而没有进行图片的跟踪扫描之后才显示
3.这边用的是调试工具里面的android_16 的demo来进行的测试 但是看了源码后发现ARProjectManager这个类的函数跳转其中
`private static void launchARActivity(Context context, int arType, String arContentPath) {
        JSONObject jsonObject = new JSONObject();
        try {
            jsonObject.put("type", arType);
            jsonObject.put("path", arContentPath);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        Intent intent = new Intent(context, ARActivity.class);
        intent.putExtra(Constants.AR_KEY, "7efdfd245e20796a58dbf49da346deef");
        intent.putExtra(Constants.AR_TYPE, arType);
        intent.putExtra("ar_sample_info", jsonObject.toString());
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        context.startActivity(intent);
    }`
跳转到ARActivity后并没有使用intent中的intent.putExtra("ar_sample_info", jsonObject.toString());这个参数
请问你们的ARFragment是怎么识别我所打开的是哪个模型呢？我这边可能源码看的不仔细 希望能解答下我的困惑

**Comment by mayimchen** [comment]
@NQPE 
2. 一进入就显示与 AR/AR_Sample/ar-video/ar/res/simple_scene.json 中 字段"showImmediately": 1 配置相关
3. 以函数参数为标准，内部实现不用关注。

**Comment by AngusShyang** [comment]
@NQPE 
1. 第一个Sample 为tracking类型、需要扫描该项目包ar/models/image_target.png图片即可触发显示, 或扫描AR_Sample目录下tracing图片也可触发.

**Comment by NQPE** [comment]
@AngusShyang 
1.透明视频问题  我用了AR/AR_Sample/ar-tracking-video/ar/ 这个透明视频demo 并且扫描了image_target.png图片 而且明显感觉是扫描成功了的 因为一开始进入ARActivity的的扫描动画效果消失了
但是手机上不出现透明视频的画面 然后我这边换了两个android手机魅族5和华为荣耀8都是这个问题 感觉都是扫描成功了 但是没有视频画面 
我让IOS同事跑了AR/AR_Sample/ar-tracking-video/ar/ 这个透明视频demo 在IOS上透明视频正常显示

希望解释一下为何会出现这种情况？
