### ISSUE TITLE
Demo 中的图片为什么是一张黑色图片

### ISSUE THREAD

**Issue by Sirormy** [baidu/AR#4]
百度提供的很多 AR Demo 中这张 image_target.png 都是一张纯黑色图片，这里不应该是待识别的图片吗？ 这张是需要直接替换还是训练后再替换？
https://github.com/baidu/AR/blob/master/AR_Sample/ar-slam/ar/models/image_target.png

**Comment by SXCC** [comment]
ar/models 文件夹下的文件为图像训练算法输出的跟踪模型文件（包含三个二进制文件，一个roi.txt,  一张识别图），其中只有三个二进制文件是Demo运行时需要被使用的。所以为了减小资源包的包大小，很多Demo中将image_target.png替换成了一张小尺寸的空白图片。

**Comment by Sirormy** [comment]
@SXCC 那要想使用自己的图片是直接替换图片就可以了吗，还是需要将训练产生的二进制文件也替换掉，没找到关于训练之类的东西。

**Comment by AngusShyang** [comment]
可以直接换掉、图片名称请不要变动即可

**Comment by SXCC** [comment]
如果希望demo里能跟踪自己的识别图的话，需要到 https://dumix.baidu.com/ 创建一个项目，提交识别图，后台会执行训练，提供跟踪模型文件的下载链接，

**Comment by Sirormy** [comment]
@AngusShyang  确实图片换掉就可以了，训练后下载的文件只有 roi.txt 里的信息是变动过的，里边只有坐标信息，不是很明白。

**Comment by Sirormy** [comment]
@SXCC 看到了，谢谢。
